// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "layoutmastergo/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ContainerRepository is an autogenerated mock type for the ContainerRepository type
type ContainerRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ContainerRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, page, pageSize
func (_m *ContainerRepository) GetAll(ctx context.Context, page int, pageSize int) ([]models.Container, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Container, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Container); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, query, page, pageSize
func (_m *ContainerRepository) Search(ctx context.Context, query string, page int, pageSize int) ([]models.Container, error) {
	ret := _m.Called(ctx, query, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []models.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Container, error)); ok {
		return rf(ctx, query, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Container); ok {
		r0 = rf(ctx, query, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, query, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ContainerRepository) GetByID(ctx context.Context, id uint) (*models.Container, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Container, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Container); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, container
func (_m *ContainerRepository) Save(ctx context.Context, container *models.Container) error {
	ret := _m.Called(ctx, container)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Container) error); ok {
		r0 = rf(ctx, container)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, container
func (_m *ContainerRepository) Update(ctx context.Context, id uint, container *models.Container) error {
	ret := _m.Called(ctx, id, container)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *models.Container) error); ok {
		r0 = rf(ctx, id, container)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewContainerRepository creates a new instance of ContainerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerRepository {
	mock := &ContainerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
