// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "layoutmastergo/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ItemContainerRepository is an autogenerated mock type for the ItemContainerRepository type
type ItemContainerRepository struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: ctx, item
func (_m *ItemContainerRepository) AddItem(ctx context.Context, item *models.ItemContainer) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ItemContainer) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveItem provides a mock function with given fields: ctx, containerID, productID
func (_m *ItemContainerRepository) RemoveItem(ctx context.Context, containerID uint, productID uint) error {
	ret := _m.Called(ctx, containerID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, containerID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateQuantity provides a mock function with given fields: ctx, containerID, productID, quantity
func (_m *ItemContainerRepository) UpdateQuantity(ctx context.Context, containerID uint, productID uint, quantity int) error {
	ret := _m.Called(ctx, containerID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, int) error); ok {
		r0 = rf(ctx, containerID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewItemContainerRepository creates a new instance of ItemContainerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemContainerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemContainerRepository {
	mock := &ItemContainerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
